version: '3.7'
services:
  rasa:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./models:/app/models
    command: bash -c "rm -rf models/* && rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\" -p 8080 --debug"
    ports:
    - '8080:8080' #external:internal
    networks:
    - all

  rasa-action:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

#  web:
#      image: rasa-frontend:latest
#      build: "./"
#      restart: always
#      ports:
#        - "80:80"

networks:
  all:
    driver: bridge
#    driver_opts:
#      com.docker.network.enable.ipv6: "true"